//! Hermetic tests for the offline workspace graph builder (no network).

use std::fs;
use std::path::Path;

use dependable_fetch::{
    DependencyGraph, GraphSource, NodeKind, TreeOptions, WorkspaceGraphOptions,
    build_workspace_graph,
};
use tempfile::TempDir;

/// A three-member workspace (a -> b -> c, a -> serde) with a realistic v4
/// `Cargo.lock` that includes a git dep and a duplicate-version external.
fn write_workspace(dir: &Path) {
    fs::write(
        dir.join("Cargo.toml"),
        r#"
[workspace]
resolver = "2"
members = ["crates/a", "crates/b", "crates/c"]
exclude = ["crates/legacy"]
"#,
    )
    .unwrap();

    let members = [
        (
            "a",
            r#"
[package]
name = "a"
version = "0.1.0"

[dependencies]
b = { path = "../b" }
serde = "1"
gitdep = { git = "https://example.com/gitdep" }
"#,
        ),
        (
            "b",
            r#"
[package]
name = "b"
version = "0.1.0"

[dependencies]
c = { path = "../c" }
serde = "1"
"#,
        ),
        (
            "c",
            r#"
[package]
name = "c"
version = "0.1.0"
"#,
        ),
    ];
    for (name, manifest) in members {
        let crate_dir = dir.join("crates").join(name);
        fs::create_dir_all(&crate_dir).unwrap();
        fs::write(crate_dir.join("Cargo.toml"), manifest).unwrap();
    }
    // An excluded crate that must NOT be treated as a workspace member.
    let legacy = dir.join("crates").join("legacy");
    fs::create_dir_all(&legacy).unwrap();
    fs::write(
        legacy.join("Cargo.toml"),
        "[package]\nname = \"legacy\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
}

fn write_lockfile(dir: &Path) {
    fs::write(
        dir.join("Cargo.lock"),
        r#"# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "a"
version = "0.1.0"
dependencies = [
 "b",
 "gitdep",
 "serde",
]

[[package]]
name = "b"
version = "0.1.0"
dependencies = [
 "c",
 "serde",
]

[[package]]
name = "c"
version = "0.1.0"

[[package]]
name = "gitdep"
version = "0.2.0"
source = "git+https://example.com/gitdep#abc123"

[[package]]
name = "serde"
version = "1.0.200"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "syn 2.0.0",
]

[[package]]
name = "syn"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "syn"
version = "2.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
"#,
    )
    .unwrap();
}

/// The version of one node, panicking if there is no such node — so an assertion
/// about a node cannot silently pass because the node is missing.
fn version_of<'g>(graph: &'g DependencyGraph, name: &str) -> Option<&'g str> {
    graph
        .nodes()
        .iter()
        .find(|n| n.name == name)
        .unwrap_or_else(|| panic!("node {name} missing"))
        .version
        .as_deref()
}

fn kind_of(graph: &DependencyGraph, name: &str) -> NodeKind {
    graph
        .nodes()
        .iter()
        .find(|n| n.name == name)
        .unwrap_or_else(|| panic!("node {name} missing"))
        .kind
}

/// Depth-first flatten of every reachable `(name, deduped)`.
fn flatten(graph: &DependencyGraph) -> Vec<(String, bool)> {
    fn walk(
        graph: &DependencyGraph,
        n: &dependable_fetch::TreeNode,
        out: &mut Vec<(String, bool)>,
    ) {
        out.push((graph.nodes()[n.node].name.clone(), n.deduped()));
        for c in &n.children {
            walk(graph, c, out);
        }
    }
    let tree = graph.tree(&TreeOptions::default());
    let mut out = Vec::new();
    for r in &tree.roots {
        walk(graph, r, &mut out);
    }
    out
}

#[test]
fn builds_resolved_graph_from_lockfile() {
    let tmp = TempDir::new().unwrap();
    write_workspace(tmp.path());
    write_lockfile(tmp.path());

    let built = build_workspace_graph(tmp.path(), &WorkspaceGraphOptions::default()).unwrap();
    assert_eq!(built.source, GraphSource::Lockfile);
    let g = &built.graph;

    // Classification: members vs external vs git.
    assert_eq!(kind_of(g, "a"), NodeKind::Workspace);
    assert_eq!(kind_of(g, "b"), NodeKind::Workspace);
    assert_eq!(kind_of(g, "c"), NodeKind::Workspace);
    assert_eq!(kind_of(g, "serde"), NodeKind::Registry);
    assert_eq!(kind_of(g, "gitdep"), NodeKind::Git);

    // The excluded crate is not a member.
    assert!(g.nodes().iter().all(|n| n.name != "legacy"));

    // Inter-member edge a -> b, and the duplicate syn versions are distinct.
    let flat = flatten(g);
    assert!(flat.iter().any(|(n, _)| n == "a"));
    assert!(flat.iter().any(|(n, _)| n == "b"));
    // serde appears once fully and once deduped (under a and under b).
    let serde_full = flat.iter().filter(|(n, d)| n == "serde" && !d).count();
    let serde_dedup = flat.iter().filter(|(n, d)| n == "serde" && *d).count();
    assert_eq!(serde_full, 1);
    assert!(serde_dedup >= 1);
}

#[test]
fn duplicate_versions_are_distinct_nodes() {
    let tmp = TempDir::new().unwrap();
    write_workspace(tmp.path());
    write_lockfile(tmp.path());
    let built = build_workspace_graph(tmp.path(), &WorkspaceGraphOptions::default()).unwrap();
    let versions: Vec<Option<&str>> = built
        .graph
        .nodes()
        .iter()
        .filter(|n| n.name == "syn")
        .map(|n| n.version.as_deref())
        .collect();
    assert!(versions.contains(&Some("1.0.0")));
    assert!(versions.contains(&Some("2.0.0")));
}

#[test]
fn invert_reaches_dependents() {
    let tmp = TempDir::new().unwrap();
    write_workspace(tmp.path());
    write_lockfile(tmp.path());
    // Root the (inverted) graph at serde: it should reach a and b.
    let mut opts = WorkspaceGraphOptions::default();
    opts.package = Some("serde".to_owned());
    let built = build_workspace_graph(tmp.path(), &opts).unwrap();
    let inverted = built.graph.inverted();
    let flat = flatten(&inverted);
    let names: Vec<&str> = flat.iter().map(|(n, _)| n.as_str()).collect();
    assert!(names.contains(&"serde"));
    assert!(names.contains(&"a"));
    assert!(names.contains(&"b"));
}

#[test]
fn falls_back_to_shallow_graph_without_lockfile() {
    let tmp = TempDir::new().unwrap();
    write_workspace(tmp.path()); // no lockfile written

    let built = build_workspace_graph(tmp.path(), &WorkspaceGraphOptions::default()).unwrap();
    assert_eq!(built.source, GraphSource::Manifests);
    let g = &built.graph;

    // Members are still classified as workspace, and their direct external and
    // git deps are present with the right kinds.
    assert_eq!(kind_of(g, "a"), NodeKind::Workspace);
    assert_eq!(kind_of(g, "serde"), NodeKind::Registry);
    assert_eq!(kind_of(g, "gitdep"), NodeKind::Git);

    // The inter-member edge a -> b survives from the path dependency.
    let flat = flatten(g);
    let a = flat.iter().position(|(n, _)| n == "a");
    assert!(a.is_some());
    assert!(flat.iter().any(|(n, _)| n == "b"));

    // A member's own version is declared, not resolved: `crates/a` says
    // `version = "0.1.0"` and that *is* what the crate is, lockfile or not.
    let version_of = |name: &str| {
        g.nodes()
            .iter()
            .find(|n| n.name == name)
            .unwrap_or_else(|| panic!("a node for {name}"))
            .version
            .as_deref()
    };
    assert_eq!(version_of("a"), Some("0.1.0"));
    assert_eq!(version_of("b"), Some("0.1.0"));
    assert_eq!(version_of("c"), Some("0.1.0"));

    // A dependency is the other case: the manifest declares a constraint, and
    // nothing here resolved it. The graph says so rather than recording a blank
    // string that reads downstream as a version.
    assert_eq!(version_of("serde"), None);
    assert_eq!(version_of("gitdep"), None);
    assert!(
        g.nodes().iter().all(|n| n.version != Some(String::new())),
        "and never the empty string"
    );
}

/// A member with `version.workspace = true` still has a version — the root's
/// `[workspace.package]` declares it, and the root is already read here. Reading
/// only the literal would report every member of a version-inheriting workspace
/// as unknown, which is the majority shape for a Cargo workspace.
#[test]
fn a_member_inheriting_its_version_from_the_workspace_root_still_reports_one() {
    let tmp = TempDir::new().unwrap();
    let dir = tmp.path();
    fs::write(
        dir.join("Cargo.toml"),
        r#"
[workspace]
resolver = "2"
members = ["crates/a"]

[workspace.package]
version = "3.1.4"
"#,
    )
    .unwrap();
    let crate_dir = dir.join("crates").join("a");
    fs::create_dir_all(&crate_dir).unwrap();
    fs::write(
        crate_dir.join("Cargo.toml"),
        r#"
[package]
name = "a"
version.workspace = true
"#,
    )
    .unwrap();

    let built = build_workspace_graph(dir, &WorkspaceGraphOptions::default()).unwrap();
    assert_eq!(built.source, GraphSource::Manifests);
    let a = built
        .graph
        .nodes()
        .iter()
        .find(|n| n.name == "a")
        .expect("a node for the member");
    assert_eq!(a.version.as_deref(), Some("3.1.4"));
}

/// The walk descends into a nested, **independent** workspace — a `cargo fuzz` or
/// `examples/` tree with its own `[workspace]` — because Cargo already ignores such
/// a subtree, so nobody lists it in `[workspace] exclude`. The outer root has no
/// authority over those crates, so its `[workspace.package] version` must not be
/// handed to them. The nested root's own table is the one that governs them, and it
/// is one directory up from the crate: reading it is what turns "no version" into
/// the right one rather than a confidently wrong one.
/// A version the nested crate states outright is still its own, and still reported.
#[test]
fn a_nested_independent_workspaces_crate_resolves_against_its_own_root() {
    let tmp = TempDir::new().unwrap();
    let dir = tmp.path();
    fs::write(
        dir.join("Cargo.toml"),
        r#"
[workspace]
resolver = "2"
members = ["crates/a"]

[workspace.package]
version = "1.0.0"
"#,
    )
    .unwrap();
    let member = dir.join("crates").join("a");
    fs::create_dir_all(&member).unwrap();
    fs::write(
        member.join("Cargo.toml"),
        r#"
[package]
name = "a"
version.workspace = true
"#,
    )
    .unwrap();
    let fuzz = dir.join("fuzz");
    fs::create_dir_all(&fuzz).unwrap();
    fs::write(
        fuzz.join("Cargo.toml"),
        r#"
[workspace]

[workspace.package]
version = "0.0.0"

[package]
name = "a-fuzz"
version.workspace = true
"#,
    )
    .unwrap();
    // A crate below the nested root is out of reach too, however deep.
    let inner = fuzz.join("crates").join("stated");
    fs::create_dir_all(&inner).unwrap();
    fs::write(
        inner.join("Cargo.toml"),
        r#"
[package]
name = "a-fuzz-stated"
version = "7.7.7"
"#,
    )
    .unwrap();

    let built = build_workspace_graph(dir, &WorkspaceGraphOptions::default()).unwrap();
    assert_eq!(built.source, GraphSource::Manifests);
    let g = &built.graph;
    assert_eq!(version_of(g, "a"), Some("1.0.0"));
    assert_eq!(
        version_of(g, "a-fuzz"),
        Some("0.0.0"),
        "a nested workspace's crate inherits from the nested root, never the outer one"
    );
    assert_eq!(
        version_of(g, "a-fuzz-stated"),
        Some("7.7.7"),
        "and a version the crate states outright is still its own"
    );
}

/// The guard on the fix above: a nested root that declares a `[workspace]` and no
/// `[workspace.package]` resolves its members' `version.workspace = true` to
/// nothing. Reaching past it to the outer root's `1.0.0` would be the bug the
/// scope stack exists to prevent, dressed up as a fallback.
#[test]
fn a_nested_root_declaring_no_version_leaves_its_crate_without_one() {
    let tmp = TempDir::new().unwrap();
    let dir = tmp.path();
    fs::write(
        dir.join("Cargo.toml"),
        r#"
[workspace]
resolver = "2"
members = ["crates/a"]

[workspace.package]
version = "1.0.0"
"#,
    )
    .unwrap();
    let member = dir.join("crates").join("a");
    fs::create_dir_all(&member).unwrap();
    fs::write(
        member.join("Cargo.toml"),
        r#"
[package]
name = "a"
version.workspace = true
"#,
    )
    .unwrap();
    let silent = dir.join("silent");
    fs::create_dir_all(&silent).unwrap();
    fs::write(
        silent.join("Cargo.toml"),
        r#"
[workspace]

[package]
name = "silent"
version.workspace = true
"#,
    )
    .unwrap();

    let built = build_workspace_graph(dir, &WorkspaceGraphOptions::default()).unwrap();
    assert_eq!(built.source, GraphSource::Manifests);
    let g = &built.graph;
    assert_eq!(version_of(g, "a"), Some("1.0.0"));
    assert_eq!(
        version_of(g, "silent"),
        None,
        "its own root declares no version, and the outer root's is not a fallback"
    );
}

/// Workspaces nest more than one deep — a `fuzz/` tree that itself vendors an
/// example workspace. The governing root is the *nearest* `[workspace]` ancestor,
/// so the innermost one wins, for the crate that declares it and for everything
/// below it.
#[test]
fn the_innermost_workspace_root_governs_when_workspaces_nest_twice() {
    let tmp = TempDir::new().unwrap();
    let dir = tmp.path();
    fs::write(
        dir.join("Cargo.toml"),
        r#"
[workspace]
resolver = "2"

[workspace.package]
version = "1.0.0"
"#,
    )
    .unwrap();
    let outer_member = dir.join("crates").join("a");
    fs::create_dir_all(&outer_member).unwrap();
    fs::write(
        outer_member.join("Cargo.toml"),
        r#"
[package]
name = "a"
version.workspace = true
"#,
    )
    .unwrap();
    let mid = dir.join("mid");
    fs::create_dir_all(&mid).unwrap();
    fs::write(
        mid.join("Cargo.toml"),
        r#"
[workspace]

[workspace.package]
version = "2.0.0"

[package]
name = "mid"
version.workspace = true
"#,
    )
    .unwrap();
    let inner = mid.join("inner");
    fs::create_dir_all(&inner).unwrap();
    fs::write(
        inner.join("Cargo.toml"),
        r#"
[workspace]

[workspace.package]
version = "3.0.0"

[package]
name = "inner"
version.workspace = true
"#,
    )
    .unwrap();
    let leaf = inner.join("crates").join("leaf");
    fs::create_dir_all(&leaf).unwrap();
    fs::write(
        leaf.join("Cargo.toml"),
        r#"
[package]
name = "leaf"
version.workspace = true
"#,
    )
    .unwrap();

    let built = build_workspace_graph(dir, &WorkspaceGraphOptions::default()).unwrap();
    assert_eq!(built.source, GraphSource::Manifests);
    let g = &built.graph;
    assert_eq!(version_of(g, "a"), Some("1.0.0"));
    // A manifest that is both a `[workspace]` and a `[package]` resolves against
    // itself, not against the root that contains it.
    assert_eq!(version_of(g, "mid"), Some("2.0.0"));
    assert_eq!(version_of(g, "inner"), Some("3.0.0"));
    assert_eq!(
        version_of(g, "leaf"),
        Some("3.0.0"),
        "the nearest [workspace] ancestor governs, not the outermost"
    );
}

/// `[workspace.dependencies]` is the second thing a root lends its members, and it
/// decides what a `dep.workspace = true` crate *is*. It is scoped exactly like
/// `[workspace.package]`: a nested workspace's crate takes its own root's
/// declaration, so a name that root vendors by path is a path crate, even though
/// the outer root declares the same shape of entry as a registry one.
///
/// The two names are deliberately different: one node carries one name, so a name
/// declared on both sides could not distinguish which root was consulted.
#[test]
fn a_nested_workspaces_crate_inherits_dependencies_from_its_own_root() {
    let tmp = TempDir::new().unwrap();
    let dir = tmp.path();
    fs::write(
        dir.join("Cargo.toml"),
        r#"
[workspace]
resolver = "2"

[workspace.dependencies]
outer-dep = "1"
nested-dep = "1"
"#,
    )
    .unwrap();
    let outer_member = dir.join("crates").join("outer");
    fs::create_dir_all(&outer_member).unwrap();
    fs::write(
        outer_member.join("Cargo.toml"),
        r#"
[package]
name = "outer"
version = "0.1.0"

[dependencies]
outer-dep.workspace = true
"#,
    )
    .unwrap();
    let nested = dir.join("nested");
    fs::create_dir_all(&nested).unwrap();
    fs::write(
        nested.join("Cargo.toml"),
        r#"
[workspace]

[workspace.dependencies]
nested-dep = { path = "../vendor/nested-dep" }

[package]
name = "nested"
version = "0.1.0"

[dependencies]
nested-dep.workspace = true
"#,
    )
    .unwrap();

    let built = build_workspace_graph(dir, &WorkspaceGraphOptions::default()).unwrap();
    assert_eq!(built.source, GraphSource::Manifests);
    let g = &built.graph;
    assert_eq!(kind_of(g, "outer-dep"), NodeKind::Registry);
    // The outer root declares `nested-dep = "1"` too, and consulting it would make
    // this a registry crate. The nested root is the one with authority here.
    assert_eq!(
        kind_of(g, "nested-dep"),
        NodeKind::Path,
        "a nested workspace's crate inherits from the nested root's declarations"
    );
}

/// Without a lockfile the graph is built from manifests alone, and a member's
/// `dep.workspace = true` says nothing about what the crate *is*. The root's declaration
/// does, and the root is already read here — so `centrally_declared` is classified from
/// what the root says it is, not from a guess that would make every inherited crate a
/// registry one (or, before inheritance existed at all, a local path).
#[test]
fn the_root_decides_what_an_inherited_dependency_is_in_the_shallow_graph() {
    let tmp = TempDir::new().unwrap();
    fs::write(
        tmp.path().join("Cargo.toml"),
        "[workspace]\nresolver = \"2\"\nmembers = [\"crates/a\"]\n\n[workspace.dependencies]\nserde = \"1\"\ncentrally_declared = { path = \"vendor/v\" }\n",
    )
    .unwrap();
    fs::create_dir_all(tmp.path().join("crates/a")).unwrap();
    fs::write(
        tmp.path().join("crates/a/Cargo.toml"),
        "[package]\nname = \"a\"\nversion = \"0.1.0\"\n\n[dependencies]\nserde.workspace = true\ncentrally_declared.workspace = true\nvendored = { path = \"../../vendor/v\" }\n",
    )
    .unwrap();

    let built = build_workspace_graph(tmp.path(), &WorkspaceGraphOptions::default()).unwrap();
    assert_eq!(built.source, GraphSource::Manifests);

    assert_eq!(kind_of(&built.graph, "serde"), NodeKind::Registry);
    // Declared centrally as a path, so it is a path crate wherever it is used — the case
    // a "an inherited entry is probably a registry crate" guess gets wrong.
    assert_eq!(kind_of(&built.graph, "centrally_declared"), NodeKind::Path);
    // And a member's own path entry, which never depended on the root at all.
    assert_eq!(kind_of(&built.graph, "vendored"), NodeKind::Path);
}

/// Without a lockfile a dependency's version is normally unknown, because a
/// manifest declares a constraint rather than a resolution. `= "1.0.200"` is the
/// exception: it admits exactly one release, so the manifest has already resolved
/// it and calling it unknown understates what was read.
///
/// Cargo's `"1"` beside it is the control. It looks concrete and is a caret range
/// over every 1.x release, which is why the rule cannot be "the string has three
/// numbers in it".
#[test]
fn an_exactly_pinned_dependency_reports_its_version_without_a_lockfile() {
    let tmp = TempDir::new().unwrap();
    fs::write(
        tmp.path().join("Cargo.toml"),
        "[workspace]\nresolver = \"2\"\nmembers = [\"crates/a\"]\n",
    )
    .unwrap();
    fs::create_dir_all(tmp.path().join("crates/a")).unwrap();
    fs::write(
        tmp.path().join("crates/a/Cargo.toml"),
        "[package]\nname = \"a\"\nversion = \"0.1.0\"\n\n\
         [dependencies]\n\
         serde = \"=1.0.200\"\n\
         regex = \"1\"\n\
         partial = \"=1.2\"\n\
         gitdep = { git = \"https://example.com/gitdep\", version = \"=1.2.3\" }\n\
         localdep = { path = \"../../vendor/v\", version = \"=4.5.6\" }\n",
    )
    .unwrap();

    let built = build_workspace_graph(tmp.path(), &WorkspaceGraphOptions::default()).unwrap();
    assert_eq!(built.source, GraphSource::Manifests);
    let g = &built.graph;

    assert_eq!(version_of(g, "serde"), Some("1.0.200"));
    // A caret range over every 1.x release names no single one of them.
    assert_eq!(version_of(g, "regex"), None);
    // `=1.2` is exact only to the minor: Cargo still accepts every 1.2.x patch.
    assert_eq!(version_of(g, "partial"), None);
    // Candidacy is `Item::is_checkable()`, which a git or path source fails
    // whatever version is written beside it. These are the crate at that location,
    // not the crate the registry publishes under that number.
    assert_eq!(version_of(g, "gitdep"), None);
    assert_eq!(version_of(g, "localdep"), None);
    assert_eq!(kind_of(g, "gitdep"), NodeKind::Git);
    assert_eq!(kind_of(g, "localdep"), NodeKind::Path);

    // The member's own version is read from `[package] version` and is untouched
    // by any of this.
    assert_eq!(version_of(g, "a"), Some("0.1.0"));
    assert!(
        g.nodes().iter().all(|n| n.version != Some(String::new())),
        "and never the empty string"
    );
}

/// A member's `dep.workspace = true` carries no version of its own; the root's
/// `[workspace.dependencies]` entry does, and inheritance is already resolved
/// before the graph is assembled. So a centrally pinned crate reports the pin the
/// root declared — the shape most workspaces that pin anything actually use.
#[test]
fn a_centrally_pinned_inherited_dependency_reports_the_roots_version() {
    let tmp = TempDir::new().unwrap();
    fs::write(
        tmp.path().join("Cargo.toml"),
        "[workspace]\nresolver = \"2\"\nmembers = [\"crates/a\"]\n\n\
         [workspace.dependencies]\n\
         serde = \"=1.0.200\"\n\
         regex = \"1\"\n",
    )
    .unwrap();
    fs::create_dir_all(tmp.path().join("crates/a")).unwrap();
    fs::write(
        tmp.path().join("crates/a/Cargo.toml"),
        "[package]\nname = \"a\"\nversion = \"0.1.0\"\n\n\
         [dependencies]\nserde.workspace = true\nregex.workspace = true\n",
    )
    .unwrap();

    let built = build_workspace_graph(tmp.path(), &WorkspaceGraphOptions::default()).unwrap();
    assert_eq!(built.source, GraphSource::Manifests);
    assert_eq!(version_of(&built.graph, "serde"), Some("1.0.200"));
    assert_eq!(version_of(&built.graph, "regex"), None);
}

/// One node per name across the whole workspace, so a version may only be carried
/// when every member that declares the crate agrees on it. Reporting the first
/// would make the graph depend on the order the directory walk found the members
/// in, and would state a version the other member's manifest contradicts.
#[test]
fn two_members_that_pin_one_crate_differently_resolve_to_nothing() {
    let tmp = TempDir::new().unwrap();
    fs::write(
        tmp.path().join("Cargo.toml"),
        "[workspace]\nresolver = \"2\"\nmembers = [\"crates/a\", \"crates/b\"]\n",
    )
    .unwrap();
    for (member, serde, agreed) in [("a", "=1.0.200", "=1.0.0"), ("b", "=1.0.201", "=1.0.0")] {
        fs::create_dir_all(tmp.path().join("crates").join(member)).unwrap();
        fs::write(
            tmp.path().join("crates").join(member).join("Cargo.toml"),
            format!(
                "[package]\nname = \"{member}\"\nversion = \"0.1.0\"\n\n\
                 [dependencies]\nserde = \"{serde}\"\nagreed = \"{agreed}\"\n"
            ),
        )
        .unwrap();
    }

    let built = build_workspace_graph(tmp.path(), &WorkspaceGraphOptions::default()).unwrap();
    assert_eq!(built.source, GraphSource::Manifests);
    assert_eq!(version_of(&built.graph, "serde"), None);
    // Agreement is not ambiguity: two members naming the same release still name it.
    assert_eq!(version_of(&built.graph, "agreed"), Some("1.0.0"));
}
