//! Parser for Dart / Flutter `pubspec.lock`.
//!
//! A focused block-style YAML scanner (no general YAML dependency): under the
//! top-level `packages:` map, each package is a 2-space-indented header whose
//! 4-space-indented `version:` field gives the resolved version.

use std::collections::HashMap;

use crate::error::ParseError;
use crate::lockfiles::LockfileData;

/// Parse `pubspec.lock` into a name → resolved-version map.
pub fn parse_dart_pubspec_lock(content: &str) -> Result<LockfileData, ParseError> {
    let mut versions: HashMap<String, Vec<String>> = HashMap::new();
    let mut in_packages = false;
    let mut current: Option<String> = None;

    for raw in content.lines() {
        let line = strip_comment(raw);
        if line.trim().is_empty() {
            continue;
        }
        let indent = line.len() - line.trim_start().len();
        match indent {
            0 => {
                in_packages = top_level_key(line) == "packages";
                current = None;
            }
            2 if in_packages => {
                // A package header (`http:`), value empty (a nested map follows).
                current = key_of(line);
            }
            4 if in_packages => {
                if let (Some(pkg), Some((key, value))) = (current.as_ref(), split_entry(line))
                    && key == "version"
                {
                    versions.entry(pkg.clone()).or_default().push(value);
                }
            }
            _ => {}
        }
    }

    Ok(LockfileData { versions })
}

/// The top-level key of an indent-0 line (`packages:` → `packages`).
fn top_level_key(line: &str) -> &str {
    line.split(':').next().unwrap_or("").trim()
}

/// The key of a `key:` header line, if non-empty.
fn key_of(line: &str) -> Option<String> {
    let key = line.split(':').next().unwrap_or("").trim();
    (!key.is_empty()).then(|| key.to_string())
}

/// Split a `key: value` line into its trimmed, unquoted parts.
fn split_entry(line: &str) -> Option<(String, String)> {
    let colon = line.find(':')?;
    let key = line[..colon].trim().to_string();
    let value = unquote(line[colon + 1..].trim());
    if key.is_empty() || value.is_empty() {
        return None;
    }
    Some((key, value))
}

/// Strip matching surrounding quotes from a scalar.
fn unquote(value: &str) -> String {
    if value.len() >= 2
        && ((value.starts_with('"') && value.ends_with('"'))
            || (value.starts_with('\'') && value.ends_with('\'')))
    {
        value[1..value.len() - 1].to_string()
    } else {
        value.to_string()
    }
}

/// Strip a YAML line comment (`#` preceded by whitespace or at line start).
fn strip_comment(line: &str) -> &str {
    let bytes = line.as_bytes();
    let mut in_single = false;
    let mut in_double = false;
    for (i, &b) in bytes.iter().enumerate() {
        match b {
            b'\'' if !in_double => in_single = !in_single,
            b'"' if !in_single => in_double = !in_double,
            b'#' if !in_single && !in_double && (i == 0 || bytes[i - 1].is_ascii_whitespace()) => {
                return &line[..i];
            }
            _ => {}
        }
    }
    line
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::item::{Item, PackageSource};
    use crate::lockfiles::apply_lockfile;

    const LOCK: &str = "# Generated by pub\npackages:\n  http:\n    dependency: \"direct main\"\n    description:\n      name: http\n      url: \"https://pub.dev\"\n    source: hosted\n    version: \"1.1.0\"\n  provider:\n    dependency: \"direct main\"\n    source: hosted\n    version: \"6.0.5\"\nsdks:\n  dart: \">=2.12.0 <3.0.0\"\n";

    #[test]
    fn extracts_package_versions_only() {
        let data = parse_dart_pubspec_lock(LOCK).unwrap();
        assert_eq!(data.versions["http"], vec!["1.1.0"]);
        assert_eq!(data.versions["provider"], vec!["6.0.5"]);
        // The nested `description.name` and the `sdks` block are not packages.
        assert!(!data.versions.contains_key("dart"));
        assert_eq!(data.versions.len(), 2);
    }

    #[test]
    fn applies_locked_version() {
        let data = parse_dart_pubspec_lock(LOCK).unwrap();
        let mut items = vec![Item {
            name: "http".into(),
            version_constraint: "^1.1.0".into(),
            source: PackageSource::Registry,
            version_line: 0,
            version_col_start: 0,
            version_col_end: 0,
            registry: None,
            locked_version: None,
        }];
        apply_lockfile(&mut items, &data);
        assert_eq!(items[0].locked_version.as_deref(), Some("1.1.0"));
    }
}
